CRUD para receitas do Fintech
pedrohlucena/fintech-crud pull request #1
Opened 2022-10-20 11:48 UTC by pedrohlucena

2022-10-24 23:11 UTC, cgodevs requested changes

2022-10-24 23:11 UTC, cgodevs commented on fintech-crud/src/br/com/fiap/mercado/jdbc/EnterpriseDBConnection.java
> +					"RM95051",
tirar a senha 💀

2022-10-24 23:11 UTC, cgodevs commented on fintech-crud/src/br/com/fiap/mercado/view/RevenueDAOImplTest.java
> +		RevenueDAOImpl revenueDAO = new RevenueDAOImpl();
o objeto não pegou a conexão aqui, mesmo com o usuário e senha, deu certo qnd vc rodou?

2022-10-25 10:33 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/jdbc/EnterpriseDBConnection.java
> +					"RM95051",
blz oijweoijqwe

2022-10-25 10:34 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/view/RevenueDAOImplTest.java
> +		RevenueDAOImpl revenueDAO = new RevenueDAOImpl();
deu ss, n sei e o banco da fiap já voltou, vou testar aqui

2022-10-25 10:36 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/view/RevenueDAOImplTest.java
> +		RevenueDAOImpl revenueDAO = new RevenueDAOImpl();
ta retornando conexão ss, isso ta certinho

2022-10-25 10:37 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/view/RevenueDAOImplTest.java
> +		RevenueDAOImpl revenueDAO = new RevenueDAOImpl();
vdd, acabei esquecendo de por, foi alterado!

2022-10-25 10:38 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/dao/RevenueDAOImpl.java
> +			System.out.println("BLABLBLA");
joiqewoijqwejroiqweji esqueci de tirar

2022-10-25 10:40 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/dao/DAOFactory.java
> +	public static RevenueDAO getRevenueDAO() {
consegue ss, é só tipar como do tipo da interface. isto é, eu retorno um RevenueDAO nesse método. quando eu for atribuir esse retorno a uma variável, eu tipo essa variável como RevenueDAO .

é uma boa prática a gente tipar como o tipo da interface que aí não ficamos engessados em uma implementação dessa interface, conseguimos mudar a implementação sem mudar muitos trechos de código heheh

2022-10-25 10:41 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/dao/DAOFactory.java
> +package br.com.fiap.mercado.dao;
ss, mas nem faz sentido ser market, porque esse crud não é uma aplicação pra fz crud de produtos de mercado e coisas do tipo.

vou colocar como "", aí c vc tiver algo contra é só dar o papo

2022-10-25 10:56 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/mercado/entity/Revenue.java
> +	public Revenue(int userCode, double revenueValue, String revenueName, Calendar revenueDate,
sobre 1 ter description e o outro não: eu preciso dessa lógica pro meu código funcionar. isso porque quando eu instancio um objeto pra salvarn o banco de dados eu não posso instanciar com um revenueCode, visto que quem preencherá o cd_receita vai ser a sequência do banco de dados, entao pra esse caso eu usaria o construtor sem revenue code.

ao passo que, quando eu tiver recuperando um dado do banco eu já tenha o cd_receita criado a minha disposição, então ao instanciar um objeto eu usaria esse construtor com revenueCode, porque o cd_receita já foi preenchido pela sequência no banco de dados.

eles tem usos diferentes e são necessários.

sobre a description, resolvi de uma forma mais simples, o campo "description" sempre terá que ter em objetos "Revenue", só que caso não haja uma descrição a gente instancia esse objeto com o valor da propriedade "description" sendo uma string vazia. nisso, o método "insert" recebe esse objeto e salva como uma string vazia no banco. quando formos recuperar esse dado do branco ele virá como uma string vazia pra gente também

2022-10-25 12:46 UTC, cgodevs requested changes

2022-10-25 12:46 UTC, cgodevs commented on fintech-crud/src/br/com/fiap/fintech/view/RevenueDAOImplTest.java
> +		RevenueDAO revenueDAO = DAOFactory.getRevenueDAO();
como alterou a instância aqui para um RevenueDAO, agora a classe RevenueDAOImpl não está sendo usada, não seria melhor 

1. remover a RevenueDAOImpl ou 
2. voltar com ela aqui e trocar o retorno de getRevenueDAO() para RevenueDAOImpl? 
Acho legal a número 2, se não achar relevante eu já aprovo, essa é a última observação

2022-10-25 21:45 UTC, pedrohlucena commented on fintech-crud/src/br/com/fiap/fintech/view/RevenueDAOImplTest.java
> +		RevenueDAO revenueDAO = DAOFactory.getRevenueDAO();
então, a classe "RevenueDAOImpl" ta sendo usada. o método getRevenueDAO retorna um objeto RevenueDAOImpl, isto é, ao chamar todos os métodos insert, update, delete eu to usando os métodos da classe RevenueDAOImpl .

o ponto é que eu só tipei como sendo do tipo da interface e não da implementação por boa prática e facilitar manutenção de código (já dei mais detalhes do pq isso é bom anteriormente nessas conversas dessa pr heheh)

aí eu acho que seria bacana mantermos do jeito que está implementado

2022-10-25 22:12 UTC, cgodevs commented on fintech-crud/src/br/com/fiap/fintech/view/RevenueDAOImplTest.java
> +		RevenueDAO revenueDAO = DAOFactory.getRevenueDAO();
o método não está retornando um RevenueDAOImpl
![image](https://user-images.githubusercontent.com/69640514/197891896-65ed0c44-ad8b-41a7-b5a0-88fed573249b.png)

2022-10-25 22:15 UTC, cgodevs approved these changes

2022-10-25 22:36 UTC, merged